version: '3' # Version of the Docker Compose file format
services:
    nginx-proxy:
      container_name: webproxy
      image: jwilder/nginx-proxy:alpine
      restart: "always" # Always restart container
      ports:
        - "8080:80" # Port mappings in format host:container
        - "9443:443"
      networks:
        - nginx-proxy # Name of the etwork these two containers will share
      labels:
        - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy" # Label needed for Let's Encrypt companion container
      volumes: # Volumes needed for container to configure proixes and access certificates genereated by Let's Encrypt companion container
        - /var/run/docker.sock:/tmp/docker.sock:ro
        - nginx-conf:/etc/nginx/conf.d
        - nginx-vhost:/etc/nginx/vhost.d
        - html:/usr/share/nginx/html
        - certs:/etc/nginx/certs:ro

    letsencrypt-nginx-proxy-companion:
        container_name: webproxy-letsencrypt-companion
        image: jrcs/letsencrypt-nginx-proxy-companion
        restart: always
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
          - nginx-conf:/etc/nginx/conf.d
          - nginx-vhost:/etc/nginx/vhost.d
          - html:/usr/share/nginx/html
          - certs:/etc/nginx/certs:rw
        depends_on: # Make sure we start nginx proxy container first
            - nginx-proxy

networks:
    nginx-proxy: # Name of our shared network that containers will use

volumes: # Names of volumes that out containers will share. Those will persist on docker's host machine.
    nginx-conf:
    nginx-vhost:
    html:
    certs: